name: Code Formatting and Linting Check

on:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  format-check:
    runs-on: qe-ubuntu20

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install uv
          uv venv
          source .venv/bin/activate
          uv sync --all-extras && uv pip install -e .

      - name: Install Node.js dependencies
        run: |
          npm ci

      - name: Run formatting and linting checks
        run: |
          source .venv/bin/activate
          ./bin/format.sh --check
